### PR TITLE
Gs 3667 hamburger mobile fix update

### PR DESCRIPTION
**Pull request by dstangel2**

### CODE REVIEW

**Comment by m-mohr** [comment]
Some details about the changes would be appreciated!

**Comment by dstangel2** [comment]
> Some details about the changes would be appreciated especially given the large number of changes.

Added styling changes to fix the improper display when viewing STAC Browser from a mobile device. Fixed headers being displayed overlapping each other

**Comment by dstangel2** [comment]
> > Some details about the changes would be appreciated especially given the large number of changes.
> 
> Added styling changes to fix the improper display when viewing STAC Browser from a mobile device. Fixed headers being displayed overlapping each other

I also see this is everything the entire GeoPlatform team has done so I'm not sure I created my PR correctly!

**Comment by m-mohr** [comment]
Yeah, the PR needs to be fixed to only include the relevant changes.

**Pull request closed without merging**
