### PR TITLE
fix issue with relative urls not working

### PR DESCRIPTION
**Pull request by DanielJDufour**

### CODE REVIEW

**Comment by m-mohr** [comment]
This means if you specify a folder like this: `https://example.com/path/to/folder` (i.e. without trailing slash) it would remove it? I'm wondering whether we should just clarify it in docs instead by saying that the baseUrl must be a folder. If we keep this in, we should probably say folders must end with a shlash.

**Comment by DanielJDufour** [comment]
fwiw, stac-layer makes sure to add a `/` at the end if it doesn't exist ;-)
https://github.com/stac-utils/stac-layer/blob/main/src/index.js#L105

**Comment by m-mohr** [comment]
Thanks, I'll check this later.

**Comment by drwelby** [comment]
This seems to be broken in `v3.0.0-alpha.7` again, relative links to child collections update the URL fragment but do not refresh the page. The sub-URLs do load correctly. This also seems to affect loading assets on Item pages.

JS console reveals `index.js:532 Error: Cannot calculate a URI relative to another relative URI`

Example: https://radiantearth.github.io/stac-browser/#/external/ard.maxar.com/samples/v4/sample-001/order_collections/5867496013686833273_root_collection.json

**Comment by m-mohr** [comment]
Thanks for reporting it, I'll check and fix that in the next few days.

**Comment by m-mohr** [comment]
@drwelby I've committed a fix to master so that navigation works again, but it seems the GeoTiff loading issue is not a STAC Browser issue. If you encounter any other issues, please let me know (preferably via a separate issue).

**Comment by drwelby** [comment]
Thanks Matthias!

I think the Geotiff rendering is just waiting for the fixes in GeoLayer to bubble up.

**Pull request closed without merging**
