### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by m-mohr**
No need to review the "New Crowdin updates" PRs. These are automated and come from the Crowdin platform.

### CODE REVIEW

**Review by p1d1d1 — CHANGES_REQUESTED** [review]
IT OK but I've just modified texts.json in crowdin because of a translation error.
YOu caould maybe reimport the file?

**Comment by m-mohr** [comment]
@p1d1d1 I believe it should be updated now.
Was the changed message source.validationReport.disclaimer?

**Comment by p1d1d1** [comment]
> @p1d1d1 I believe it should be updated now. Was the changed message source.validationReport.disclaimer?
Correct

**Review by p1d1d1 — APPROVED** [review]
IT ok

**Comment by m-mohr** [comment]
Thank you @rnanclares and @p1d1d1 for all the translation work!

**Pull request merged**
