### PR TITLE
Add collection assets and summaries

### LINKED ISSUE #38: Show collection level assets
The [collections assets](https://github.com/radiantearth/stac-spec/tree/master/extensions/collection-assets) extension is new with 1.0.0-beta.1, and enables addition of thumbnails and metadata assets at the collection level. It'd be great to show those assets in the same way that items do - visualizing the thumbnail and giving download links to the assets. Can test with https://ergo.spacebel.be/ For example https://ergo.spacebel.be/series/eo:organisationName/VITO/urn:ogc:def:EOP:VITO:PROBAV_L2A_100M_V001

### LINKED ISSUE #45: Show Collection Summaries
The STAC Browser doesn't support Collection Summaries yet, but they are an important way to help with navigating the catalogs.

### PR DESCRIPTION
**Pull request by lossyrob**
This PR introduces two new tabs to the collection page - one for collection summaries, the other for Assets if the collection utilizes the collection-assets extension.

This also refactors the Assets tab into it's own component that is shared between the Catalog.vue and Item.vue components. The Summary tab is likewise separated out into its own component. This is in line with the goal of refactoring this codebase towards being more component based, so that other project can integrate components into their own Vue project as well as improving the readability and structure of the codebase.

This PR also solves a few other smaller issues:
- URLs that had a colon in them (e.g. https://ergo.spacebel.be/series/eo:platform) were making trouble for the resolution of relative paths. When you try to use `new URL(href, base)` and the href has a colon (e.g. `series/eo:platform`), the code interprets the colon as being part of the scheme definition of an absolute URL, and so returns what it things is a fully resolved URL (e.g. `series/eo:platform`, without utilizing the base). The workaround escapes colon characters in the resolution while making sure the actual scheme definition denoted with `://` is not escaped.
- The `currentChildPage` and `currentItemPage` properties in the Catalog component were linked with state as well as query parameters. If there was no query parameter specified, the currentChildState would fall back to the previously set state. The problem with that method is that if you are in one Catalog, go to a different page - say page 7 - and then navigate to a child Catalog that has only 1 page of subcatalogs, the page state would remain 7 and no children would show. This PR makes it so that if there's no query parameter for the child page or item page it reverts back to page 1.

Fixes #38 
Fixes #45

### CODE REVIEW

**Comment by m-mohr** [comment]
I'll check it with STAC Index in the next days.

**Comment by m-mohr** [comment]
I checked this PR in STAC Browser. It looks pretty good and seems to work so far.

Some remarks:
- Thumbnails / Previews from Collections Assets could be shown similarly to items
- Maybe we should add the summaries to the metadata table on the right. It seems a bit counter intuitive on first sight on why some metadata is hidden in a Summaries tab and some other is directly visible.

**Review by m-mohr — APPROVED** [review]

**Comment by lossyrob** [comment]
@m-mohr updated to refactor the metadata sidebar and move the summaries to the sidebar as per your suggestion. Mind checking with stac-index again?

I think the thumbnail point is a good one, though I'm going to leave that to follow up work; I'll write an issue.

Thank you for the review!

**Comment by m-mohr** [comment]
I'll check it in the next two weeks (I'm on vacation).

**Comment by lossyrob** [comment]
Merging this; if stac-index testing reveals any issues we can handle in follow up PRs.

**Comment by m-mohr** [comment]
@lossyrob Seems to (mostly?) work, I just deployed it to stacindex.org.
The only weird thing I have found so far is that "Metadata" and "Providers" is empty here: https://stacindex.org/catalogs/astraea-earth-ondemand#/item/KCpHBnCmvPk3xPMWF2BjxD4iQb/3FNqjjCsFPVGVctGzNKTHp6QuE6NnyFBBNLAVc7Qyx8SPbn?t=assets

**Pull request merged**
